export {
  getModuleCategory,
  getModuleContentType,
  getModuleCreateRoute,
  getModuleIcon,
  getModuleMeta,
  getModuleResponseLabel,
  getModuleRoute,
  getModuleScope,
  getModuleTone,
  isBackOfficeScope,
  isFrontOfficeScope,
  isModuleBackOfficeVisible,
  isModuleFrontOfficeVisible,
  normalizeModuleScope,
} from "./moduleCatalog";
